Latest Course Finder
CodelyTV/cqrs-ddd-php-example pull request #164
Opened 2020-05-25 05:20 UTC by jalejandro3

PR con caso de Uso LastCourseFinder del curso Arquitectura Hexagonal.
No tengo mucha experiencia haciendo pruebas, para esta feature lo que hubiese tenido mas sentido es crear una collection de Courses y buscar la última de esa collection.

2020-06-03 08:55 UTC, rgomezcasas requested changes
👏👏👏

Now try with a different approach, try to create a `last_course` module that changes every `course created` is published!

Thanks!!

2020-06-03 08:55 UTC, rgomezcasas commented on src/Mooc/Courses/Application/Find/LastCourseFinder.php
> +        }
Extract to a method

2020-06-03 08:55 UTC, rgomezcasas commented on src/Mooc/Courses/Domain/Course.php
> +    private CourseCreatedAt $createdAt;
align

2020-06-03 08:55 UTC, rgomezcasas commented on src/Mooc/Courses/Domain/Course.php
> +        $this->createdAt = new CourseCreatedAt(\DateTimeImmutable::createFromMutable(new \DateTime('now')));
align

2020-06-03 08:55 UTC, rgomezcasas commented on src/Mooc/Courses/Domain/Course.php
> +        $this->createdAt = new CourseCreatedAt(\DateTimeImmutable::createFromMutable(new \DateTime('now')));
Also, move `new \DateTime('now')` to the `create`  method. If it's here, we won't be able to recreate it correctly on tests.
```php
public function __construct(CourseId $id, CourseName $name, CourseDuration $duration, DateTimeImmutable $createdAt)
```

2020-06-03 08:55 UTC, rgomezcasas commented on tests/src/Mooc/Courses/Application/Find/LastCourseFinderTest.php
> +        $this->finder->__invoke();
With the change in the constructor, you'll be able to easily test it

2020-06-03 08:55 UTC, closed without merging

2025-01-07 23:44 UTC, EnzoDosSantos commented on src/Mooc/Courses/Application/Find/LastCourseFinder.php
> +        }
Hi, i would like to know why this need a method, ty.